import {StyleSheet} from 'react-native';
import {COLORS} from '@/themes';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
  },
  pageContainer: {},
  headerContainer: {
    height: 165,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: COLORS.SUCCESS,
    paddingTop: 10,
    paddingLeft: 16,
    paddingRight: 16,
    position: 'relative',
  },
  notification: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    width: 60,
    height: 60,
    borderRadius: 100,
    borderWidth: 1.5,
    borderColor: COLORS.WHITE,
  },
  dot: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderWidth: 5,
    borderColor: COLORS.WHITE,
    borderRadius: 100,
    top: -9,
    right: -5,
    backgroundColor: COLORS.SUCCESS,
  },
  welcomeContainer: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: -30,
    backgroundColor: COLORS.WHITE,
    paddingTop: 20,
    paddingLeft: 32,
    paddingRight: 32,
    paddingBottom: 56,
  },
  title: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 25,
    color: COLORS.SUCCESS,
    marginBottom: 4,
  },
  name: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 15,
    color: COLORS.SUCCESS,
    marginBottom: 32,
  },
  balance: {
    borderRadius: 14,
    backgroundColor: COLORS.WHITE,
    paddingTop: 35,
    paddingRight: 30,
    paddingBottom: 40,
    paddingLeft: 30,
    shadowColor: '#000000',
    shadowRadius: 20,
    shadowOpacity: 1,
    elevation: 10,
  },
  label: {
    fontFamily: 'Montserrat-Bold',
    color: COLORS.BLACK,
    fontSize: 15,
  },
  unit: {
    fontFamily: 'Montserrat-Bold',
    color: COLORS.SUCCESS,
    fontSize: 20,
  },
  value: {
    fontFamily: 'Montserrat-ExtraBold',
    fontSize: 55,
    color: COLORS.SUCCESS,
    textAlign: 'center',
  },
  paymentContainer: {
    marginTop: -34,
    backgroundColor: COLORS.SECONDARY,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 24,
    paddingRight: 32,
    paddingBottom: 40,
    paddingLeft: 32,
  },
  paymentTitle: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 25,
    color: COLORS.SUCCESS,
    marginBottom: 36,
    textAlign: 'center',
  },
  textInput: {
    borderWidth: 2,
    borderColor: '#22782153',
    borderRadius: 15,
    flex: 1,
    height: 70,
    paddingLeft: 36,
    paddingRight: 36,
    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
    color: COLORS.SUCCESS,
  },
  guzogoTxt: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    color: COLORS.SUCCESS,
    opacity: 0.53,
    textAlign: 'right',
    marginBottom: 28,
  },
});
